### ISSUE TITLE
Bmk 'no such file' error

### ISSUE THREAD

**Issue by HenriVi** [bmx-ng/bmk#112]
Hi,

newest bmk update (Dec 23, 2021) produces this error when trying to run anything:
```
Building untitled1
[ 23%] Processing:untitled1.bmx
[ 86%] Compiling:untitled1.bmx.console.release.win32.x64.c
[100%] Linking:untitled1.exe
g++.exe: error: INPUT(: No such file or directory
g++.exe: error: ): No such file or directory
Build Error: Failed to link C:/BlitzMax_win32_0.129.3.45/BlitzMax/tmp/untitled1.exe
Process complete
```

If I compile previous commit and deploy that I get no error.  This is the case at least on Windows.

-Henri

**Comment by GWRon** [comment]
Dunno if the added "@" should be there or is stra... it is the only difference in the call

https://github.com/bmx-ng/bmk/commit/c2032e3a4c9230c6963da3533c0fddf3933e8172#diff-0b67dd82fe7a74bcc9efb2dd4bd86a3b5530da42da4c8bedd5ff5759d95e4de4R416

![image](https://user-images.githubusercontent.com/2625226/147408147-3f262242-fe23-4a92-adda-e582d1a39aea.png)

**Comment by GWRon** [comment]
Just in case it really just needs the `@`-removal I made it a PR ... so "click n fix".

**Comment by HenriVi** [comment]
This seems to be the one causing the issue as removing the @ sign doesn't produce the error anymore.

Good catch there Ron..

**Comment by GWRon** [comment]
So it was needed for clang.. i only googled for g++ and "at". Should refine my googling skills ;-)
