### ISSUE TITLE
Your commit on 31. Aug breaks compiling on vanilla blitzmax.

### ISSUE THREAD

**Issue by olejr** [bmx-ng/bmk#14]
Commit 'Added universal ios builds (x86+x64, armv7+arm64). '

bmk_modutil.bmx line 138 'Select file.ExtractExt(file)'

Compile error: Identifier 'ExtractExt' not found.

Linux Mint 17.2 x64

**Comment by GWRon** [comment]
Should fail with all variants, as "ExtractExt" is only available as "global Function", not as child of a Stream.

A change to `Select ExtractExt(file)` should fix that problem. 

All in all it is just a slip of the pen __file__.ExtractExt(__file__)
