### ISSUE TITLE
Importing non existant files within a module compile

### ISSUE THREAD

**Issue by davecamp** [bmx-ng/bmk#19]
Not exactly a show stopper, but inside a module source... if you import a non-existing file ( other than a non-existing .bmx file ) then the module will compile without error.

**Comment by GWRon** [comment]
Did not check the sources...but this sounds as if bcc/bmk blindly trust the user defined imports.

should be easy to fix...as long as "params" like `-ldl` are always starting with a minus sign __and__ paths are not allowed to start with that character. Same applies for dots...albeit files do not need to have a fileending...

So all in all in depends on whether you are blacklisting (the minus sign) or whitelisting (allowed fileendings).

**Comment by woollybah** [comment]
Should now fail if file not found.
