### ISSUE TITLE
bmk makelib produces DLL with no exported functions

### ISSUE THREAD

**Issue by DruggedBunny** [bmx-ng/bmk#25]
Hi Brucey,

I've been trying to build DLLs from bmx-ng using Sweenie's little MakeDLL program, with no joy, as documented here:

http://www.blitzbasic.com/Community/posts.php?topic=50045

However, using what turns out to be vanilla bmk's (undocumented?) 'makelib' option, I can build a working 32-bit DLL using this process:

http://mdt.bigbang.free.fr/blitz3dfr/_fofo/index.php?topic=2703.0

Trying the same from bmx-ng's bmk, though, I get a DLL, but it doesn't contain the exported function.

I'm wondering if you might be able to get this working in bmx-ng at some point (**and maybe 64-bit DLLs too**?). In vanilla, you just define the exported functions in mydll.def and call bmk makelib mydll.bmx -- had no idea it was so easy! Of course, it produces 32-bit DLLs only.

Here are a couple of test setups:

1) Working example (with command-line binaries to show working), built with vanilla:

http://www.hi-toro.com/blitz/temp/makelib32.zip

2) Non-working example, giving broken DLL with bmx-ng:

http://www.hi-toro.com/blitz/temp/makelib_fail.zip

See info.txt in each archive for relevant, er, info!

**Comment by davecamp** [comment]
I took a look into this this evening. It appears that the makelib switch gets ignored and an exe is produced but with a .dll extension :/

**Comment by davecamp** [comment]
@Brucey 
What's the best method/setup to debug bmk?

**Comment by GWRon** [comment]
Via maxIDE and the command line options available via menu?

Add the params you used during compiling your sample code. Then compile your bmk in debug mode. I think copying bmk sources to bmxng/bin helps.

Am 22. Juni 2017 23:24:40 MESZ, schrieb davecamp <notifications@github.com>:

**Comment by davecamp** [comment]
Using the legacy ide I get errors about cannot compile bmk_cores_win32?

**Comment by davecamp** [comment]
Although during runtime - ie compiling with relative command line options I get an exception of blitz.mod/blitz_thread.c failed to compile.

**Comment by GWRon** [comment]
There is bmx-ng/maxide.git


So this means you also are not able to compile it from commandline?

bmk makeapp -d path/to/file.bmx
?


Brucey changed defaults to "threaded" but bmk should be compiled in threaded mode anyways. Am not at my computer so I cannot test for problems now.

**Comment by davecamp** [comment]
I can't get the latest commits to compile - just get an EAV from bmk itself. I can't be dealing with EAVs for early stages of testing to build DLLs so I'm using 0.77 for windows ( very old but works ) from bmx-ng.com for the time being.

I'm compiling via the legacy compiler so it is looking in the legacy module folder for its modules... which brings me back to my original question of 'whats the best setup for debugging bmk'?

Funnily enough it compiles from the command line, maybe the bin/bmk.exe and src/bmk.bmx are out of sync in the archive that I downloaded?

**Comment by woollybah** [comment]
Latest bcc and bmk are working fine here - compiled with 1.50 - ensure your make.bmk and core.bmk are also up-to-date. Also, if you are building bmk "mt", you should probably rebuild your "mt" modules first - that often fixes bmk EAVs for me on Windows. Or just rebuild modules anyway.

**Comment by davecamp** [comment]
Yes, Good advice. I always rebuild all modules after updating anything. It seems to be the safest way to make sure everything is in check. I'll try again later today.

Meanwhile, what's your recommended setup for debugging bmk? Using the legacy compiler to compile bmk I get the bmk searching for modules in the legacy folder as opposed to modules in the NG folder. Using the NG compiler I get type errors due to the more accurate types in NG. Do you move certain files into certain locations for it to run properly?

**Comment by GWRon** [comment]
So did you place bmk sources (and the .bmk files) in bmxng/bin?
This should allow you to use the command line option in maxide (next to the compile options) 

Of course this is only needed if you need to debug bmk when doing something specific. Else you could just open bmk.bmx as you do for other projects.

**Comment by davecamp** [comment]
@GWRon 
I did yes, I give up.
I only wanted to help out getting dlls working and it has turned into a mission to get what I consider a basic setup working on a windows unit before even starting on debugging the real issue.

Anyway the original issue of DLLs not working is that the makelib switch is ignored and an .exe is built with a .dll extension. Naturally it will not work like that. I imagine it wouldn't take much to get it working properly but hey ho :O)

**Comment by GWRon** [comment]
The problem with debugging bmk isn't based on bmxng. It is the way bmk/bcc use path-recognition. In brl.basic (or retro or so) there are helper functions to get the blitzmax path. It cannot handle symlinks properly as it resolves them to their original path.

So there is...for now... no way to tell bmk via command line, where to find the bcc/modules... And then bcc should also be extended to use that manual override in its paths.

Until then you will always end in trouble debugging bmk from its own directory.


Maybe Brucey has some hints as I assume he already debugged bmk more often.

**Comment by GWRon** [comment]
> Anyway the original issue of DLLs not working is that the makelib switch is ignored and an .exe is built with a .dll extension. Naturally it will not work like that. I imagine it wouldn't take much to get it working properly but hey ho :O)

@woollybah 
Seems this is still an issue requiring some attention. And if not then the issue can get closed.

**Comment by Kerntrick** [comment]
Definitely needs attention imo.

**Comment by woollybah** [comment]
The only issue now is that exported function names in (at least) NG have prefix noise in them.

I was thinking perhaps we could add a new meta tag to define a particular function for export, in which case the function name would be exported as-is : so a function called "MyUsefulFunction" with the appropriate tag would be left completely un-munged - but you'd need to be aware that this could result in name collisions (and therefore linkage issues) were you to do this to a function of the same name in a separate module.

**Comment by GWRon** [comment]
Couldn't the makelib-thing create additional files to create aliases for the created source?
Something like the .def files or headers creating simple wrappers?
