### ISSUE TITLE
Can't import C functions from Visual Studio library

### ISSUE THREAD

**Issue by JoshKlint** [bmx-ng/bmk#26]
I have started moving my application over to BlitzMaxNG to make a 64-bit build.  I am unable to import a Visual Studio library in BMXNG.  I understand that the C++ classes in Visual Studio libraries are not compatible with the GCC compiler.  However, it should still be possible to import C functions from a Visual Studio library, as BlitzMax can.

Demo:
http://www.leadwerks.com/buildtest.zip

Forum thread here:
http://www.blitzmax.com/Community/posts.php?topic=107107

**Comment by woollybah** [comment]
.lib files are generally not compatible with GCC. You want an equivalent .a file for this.

There are several ways to create the archive file...

- You can use dlltool (part of MinGW) to create a .def file from a dll, and again to generate the .a file.
( [example usage](http://www.mingw.org/wiki/createimportlibraries) ).
- You can use ```reimp.exe```, which combines the above dlltool steps into one command ( available from mingw-utils ).
- You can use a tool like dependency walker to extract a function list from the dll for .def creation, then apply dlltool to generate the .a

For importing the .a file, you can use the following : 
```
Import "-L."
Import "-lleadwerks"
```

Also, you can throw away the .x file.
Its function is to prevent the duplication of extern function definitions in the generated headers.
By default, all declared extern functions are defined in the source header. This is generally what you want for your libraries.
However, for system libraries where the their headers are already included (for example, via windows.h) this results in the redefinition of the functions, with different parameter types, which results in a failed build. The function list in the .x file inhibits the generation of the function definitions.

**Comment by woollybah** [comment]
I'll assume all is well here now.
