### ISSUE TITLE
Imported resource .o in module not present in exe

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/bmk#27]
A binary .o imported directly by a module is added to the module static archive, but is not subsequently applied to the final binary.

Perhaps it would be better to add the import to the interface (.i) and then apply the actual import when the exe is linked (in the same way as -l is applied) ?

**Comment by davecamp** [comment]
Seems it would be better to include it during linking.

What's happens there for it to not be linked in properly? is the code being optimised out for some reason?

**Comment by woollybah** [comment]
The object appears in the archive (.a). Presumably, because the object (or a function in it, perhaps) is not directly referenced elsewhere, the object is not included in the final binary - which makes sense.

The particular problem I am dealing with is getting the wx_rc.o file (which is just a resource file with manifest, etc) into the final binary. The resource stuff is probably something that the app needs to link directly... or something. If I import it from the app, all is well.

**Comment by woollybah** [comment]
Hmmm, according to my particular case, [I may be barking up the wrong tree](http://stackoverflow.com/questions/531502/vc-resources-in-a-static-library).

Perhaps I need to come from a different direction altogether.

**Comment by davecamp** [comment]
That link also explains why linking it in when building the exe works out ok.

**Comment by woollybah** [comment]
Closing, as it's probably not an issue at all.
App needs to import a resource object directly.
