### ISSUE TITLE
possible 'remove .x file' solution

### ISSUE THREAD

**Issue by davecamp** [bmx-ng/bmk#28]
Just an idea...
I guess this relates a lot more to the Windows builds.
What are your thoughts on having what would be in the .x file defined after the Extern definition?
Such as

    Extern
    	Function GetWindowLongPtr:Byte Ptr(hWnd:Byte Ptr, index:Int)"Win32" = "LONG_PTR GetWindowLongPtr(HWND, INT)"
    EndExtern

or keep the 'max syntax and/or the 'max data types.

    Extern
    	Function GetWindowLongPtr:Byte Ptr(hWnd:Byte Ptr, index:Int)"Win32" = "GetWindowLongPtr:BBBYTE*(BBBYTE*, INT)"
    EndExtern

Would something like that allow to remove the .x file?

**Comment by woollybah** [comment]
Extern functions already supports a concept of aliasing :
```blitzmax
Extern
	Function GetWindowLongPtr:Byte Ptr(hWnd:Byte Ptr, index:Int)"Win32" = "some_other_function_name"
End Extern
```
... where ```some_other_function_name``` is used in the generated source in place of the one declared in the extern.

What's your plan B? ;-)

**Comment by davecamp** [comment]
Is it not the same thing except that you're not declaring the parameters and types?
'some_other_function_name' is the real external function name so I was thinking why not declare the real parameters that the function would use. Or am I missing something that's involved with aliasing?

**Comment by GWRon** [comment]
Is there a way to make it more noisy/verbose? I think an exclamation mark (!) Might be overseen/missed really fast.

Couldn't one reuse the existing meta-tag feature to add such commands? It increases difficulty for the lexer but it allows for a variety of commands. Of course you need to prefix options with "bmxng_" to allow other meta data with maybe the same name..or ignore that and just use explanatory names.

Disadvantage: compiler does not know if you just use a "very similar metatag" or if you just misspelled your command (aka syntax error)

**Comment by davecamp** [comment]
I've not updated just yet - it was a very busy festive season for me.
You may have done this already as the topic is closed...

As you have suggested I would use the parenthesis as a deciding factor to check for parameters and not emit a definition. If there is no parenthesis then fall back to the old way.

I'll have a play later this week.
Thanks for including this! It will help keep the code and files tidier.

**Comment by woollybah** [comment]
You'll get a warning now when it finds .x files, indicating that you should remove it and apply the contents directly to the extern'd functions.
This way, it currently supports both .x file usage and the new implementation.
I'll completely remove .x file support at a later date.
