### ISSUE TITLE
bmk fails with "illegal instruction"

### ISSUE THREAD

**Issue by olejr** [bmx-ng/bmk#29]
When my Linux dev box died some time ago, I switched to an older setup with an AMD Phenom II X4 965 cpu. Upgraded to latest bmk, bcc & pup/brl.mod. And my bmx_ng setup didn't work anymore..

After reinstalling different Linux distro's, pulling some hair, THEN digging around on google, I found that this (oldish) cpu doesn't like the commit dated may 21, 2016 (Added default simd cc_opt for x64 (-msse4)).

Commenting out the whole line in 'make.bmk' made the modules/exe's work.
Then I tried with different -msse(X), and the highest working was -msse4a.

**Comment by GWRon** [comment]
Maybe it is better to fallback to msse3 as "sse4a" is not supported by intel and "sse4a" is not compatible to "sse4" (which intel supports) ?

**Comment by GWRon** [comment]
Seems I get old :-)

Got a similar error and almost forgot what I replied here. Replacing msse4 with msse3 made a sample of my framework runnable again ... as other samples worked fine, the difference between these samples might be the usage of some missing instructions.

**Comment by GWRon** [comment]
I had now "illegal instructions" when running my "demoapp" as 64bit. Recompiled modules with MSSE3 - and it worked.

My CPU does not support "4"  - as noted, and as most of the AMDs should not support:
http://www.cpu-world.com/CPUs/K10/AMD-A-Series%20A8-3850%20AD3850WNZ43GX%20(AD3850WNGXBOX).html

http://www.pc-erfahrung.de/fileadmin/php-skripte/cpu_tabelle_info.php?ID=1650

**Comment by olejr** [comment]
threaded/non threaded maybe..? 
Not sure but think maybe at some point I got it (bmk) working, but not with threading..
