### ISSUE TITLE
Recompile code if ".bmx/sourcename.bmx. ... .s" is found

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bmk#3]
Not directly an issue, but maybe creating trouble which is not needed:

If cou compile with vanilla bmk, the the hidden folder .bmx contains the cache files of the compilation, for release builds on linux it is:
`sourcename.bmx.release.linux.x86.i`
`sourcename.bmx.release.linux.x86.o`
`sourcename.bmx.release.linux.x86.s`

When building with "NG" it gets:
`sourcename.bmx.release.linux.x86.c`
`sourcename.bmx.release.linux.x86.h`
`sourcename.bmx.release.linux.x86.i`
`sourcename.bmx.release.linux.x86.o`

See the difference is ".s" and ".c/.h".

Now to the problem: if bmk comes across a newly created file (newer than the source) it tries to use the existing files ("cache"). If your old code was compiled using the vanilla BMX, you will run into some errors blaming undefined things etc. Of course it is the same "vice versa".
This really gets important, if you use a source code from multiple projects `import "../lib/file.bmx"`.

Suggestion: next to the file date check it should check for the existence of a ".s"-file and if existing, unlink that cachefiles and recompile the corresponding sourcefile.

**Comment by woollybah** [comment]
Can you try it with the new bmk? It handles dependencies better, but I'm not sure about .s, specifically.

**Comment by GWRon** [comment]
Hmm just tried to recompile an previously "NG compiled" incarnation of TVTower using "BMK NG" and "vanilla bcc":

```
./bmk makeapp -t console -r -x "/home/ronny/Arbeit/Programmieren/BlitzMaxNG/TVTower-master/TVTower.bmx" (im Verzeichnis: /home/ronny/Arbeit/Programmieren/BlitzMax/bin)
Compiling:reflection.bmx
flat assembler  version 1.68  (32768 kilobytes memory)
4 passes, 30868 bytes.
[...]
Compiling:base.gfx.gui.backgroundbox.bmx
flat assembler  version 1.68  (32768 kilobytes memory)
3 passes, 8178 bytes.
[...]
Compiling:main.bmx
bcc: /home/marksibly/blitzmax/_src/codegen/cgfixfp_x86.cpp:464: bool fixMov(CGAsm*, CGMov*, FPStack*, int): Assertion `lhs->isfloat() && rhs->isfloat()' failed.
Aborted (core dumped)
Build Error: failed to compile /home/ronny/Arbeit/Programmieren/BlitzMaxNG/TVTower-master/source/main.bmx
Kompilierung fehlgeschlagen.
```


Doing a complete rebuild (BMK NG + bcc vanilla) works as expected.

**Comment by woollybah** [comment]
That error appears to be a "vanilla" bcc error?

**Comment by GWRon** [comment]
Yes...so this means that bmkng did not properly recompile ng-compiled sources for vanilla.

Am 29. Mai 2015 15:09:48 MESZ, schrieb Brucey <notifications@github.com>:

**Comment by GWRon** [comment]
Your latest commit 3ad3e1d0927242661202669eaf0462e7097e840c contains some changes to .s/.c-files ... but it does not fix this issue here.

While not perfect I suggest something in the likes of:
- compiling for NG
  -  ".s"-existent and newer/same age than ".bmx" (or ".o" on quickbuild)
    - remove intermediate compilation steps/files of "vanilla"
    - recompile of that source file required
- compiling for vanilla
  -  ".c"-existent and newer/same age than ".bmx" (or ".o" on quickbuild)
    - remove intermediate compilation steps/files of "NG"
    - recompile of that source file required
 
I just tried the current bmk-ng on a vanilla compiled project and it kept silent for 10 seconds, then "[100%] linking" and 15  seconds later it wrote the big pile of lines about undefined references. So it did not even bother recompiling :-).

**Comment by woollybah** [comment]
Interesting. I tried it and it worked for me, quick-building on both ng and legacy. Each quickbuild would recompile the application after having quick-built on the other, whilst quick-building a second time would result in nothing needing done.
But of course it only worked when the new bmk was used for ng and vanilla.

**Comment by GWRon** [comment]
> But of course it only worked when the new bmk was used for ng and vanilla.

This is why it needs to take care of precompiled files (check for "ancient data").

Removing all .bmx/* files of course lead to a successful compilation.

**Comment by woollybah** [comment]
Cool. So if you use the latest bmk everywhere it works as expected? :smiley_cat:

**Comment by GWRon** [comment]
Yes.

Think you can close this issue now, as this is a "one time problem" (when upgrading from "bmk to bmk-ng") this could only get overcome when removing the output of the "other" compiler.

**Comment by woollybah** [comment]
I just use the latest bmk with both ng and legacy. Given how much it improves compile times, there's not much of a reason not to... :dog:
