### ISSUE TITLE
bmk - Unexpected character : ?

### ISSUE THREAD

**Issue by braxtonrivers** [bmx-ng/bmk#47]
Building the new bmk and deploying it results in the following on Windows, using newly updated make.bmk with this base release package and updated modules https://github.com/bmx-ng/bmx-ng/releases/tag/v0.93.3.21.win32.x64

Building Modules
Unexpected character : ?
Process complete

**Comment by braxtonrivers** [comment]
This has since been resolved with the latest commit.

**Comment by Kerntrick** [comment]
This evening, I updated my bcc,bmk and all the modules updated since June and I had to make several changes to sdl/sdl/source.bmk to get it to compile from this '?' issue.  I had to move the 'libm' imports up to the top and close off all the missing '?'. (win7 btw).
