### ISSUE TITLE
BMK makelib creates .DLL and .a file

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bmk#50]
When building a .DLL with `bmk` then it creates an .a file too - should this be kept this way as default (as the .a file should not be needed) or should it be placed similar to other temporary stuff within the ("hidden") folder .bmx?

**Comment by woollybah** [comment]
I think it's fine. It (bcc) also creates a .def now.

The .def/.a can be used by GCC compilers to link against the DLL - if you aren't runtime linking.
