### ISSUE TITLE
Quick Build not picking up changes to incbin content

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/bmk#52]
As per the title, after adding a couple of new incbins to maxide, with Quick Build enabled, the build did not generate/compile the incbin object file, leading to undefined refs.

**Comment by GWRon** [comment]
But isn't this some kind of "desired" behaviour? Are you talking about "q" or "quick" [scan] ?

It should behave similar to the "quick scan" way: still checking local files but assume modules to be "ready".

**Comment by woollybah** [comment]
I'm fairly sure, if you add an incbin to your app, that you might expect the next quick build to correctly compile everything into the executable.

**Comment by GWRon** [comment]
This is why I differentiated between "q" (skip "recompilation" if no changes were done) and "quick" (which eg skips module checks - which might have incbin stuff too).
