### ISSUE TITLE
Bad escape sequence in string

### ISSUE THREAD

**Issue by HurryStarfish** [bmx-ng/bmk#55]
I can no longer compile bmk, as I am getting afromentioned error on this line: https://github.com/bmx-ng/bmk/blob/8fb293db4e7cbd51d2f17e006ab252c35a57b9ad/bmk.bmx#L489

**Comment by GWRon** [comment]
Seems there is a tiny tilde missing ... Will PR a little fix

**Comment by GWRon** [comment]
Interestingly the function "BmxUnquote" (in config.bmx of bcc-sources) catches "~d". 

Both, "~dp0" and "~d" get pass any current checks when using `print`.
