### ISSUE TITLE
BMK makelib - not able to avoid .def generation (no -def relay)

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bmk#58]
When telling BMK to "makelib" a sharedlib then it automatically passes "-def" to BCC calls. Creating .def files even if not desired so.

Maybe we should consider adding "nodef" similar to "nomanifest" or "nostrictmode". This way we could - for whatever reason it might be desired - disable .def generation from within the initial BMK build call.

**Comment by woollybah** [comment]
Next, you'll be wanting it to also build a basic header file too :-p

**Comment by GWRon** [comment]
Seems my reply-by-mail is no longer appearing here (they will close that notification-service at the end of the month - so maybe there are first effects visible now).
----

Nah, have written a basic tool handling it in a very primitive and error prone way.

But ... keep in in your "TODO list of 2021".

**Comment by GWRon** [comment]
Seriously: If there is a need to NOT create a .def file then it should be exposed to BMK too - or how would you create a DLL file then without creating a new .def file each time (except for removing write-permission to the .def file before building the DLL) ?

**Comment by woollybah** [comment]
Added nodef and nohead options for bmk.
(there's not currently a header generated)
