### ISSUE TITLE
gcc is now PIE on latest linux (ubuntu)

### ISSUE THREAD

**Issue by markcwm** [bmx-ng/bmk#61]
Hi,

I've just install NG on a 32-bit ubuntu 18.04 (bionic) which is nice but I found it compiles executables as shared libraries, you can run these from the Terminal but not double-click from the file manager. I found out this is due to position-independent executables (pie) now being enabled by default in GCC.

There's two solutions mentioned here https://wiki.ubuntu.com/SecurityTeam/PIE but I could only get the no-pie one to work. I tried adding to custom.bmk which only seems to work for addlinuxccopt, I get nothing with addlinuxldopt. The problem is this is a ld option and doesn't work as cc, so I had to edit bmk_util.bmx adding at line 446:
`	sb.Append(" -fPIE -no-pie")`
There's also -fPIC which works too but it seems to be related to using shared libraries whereas PIE is for executables. I tested and it doesn't affect earlier distros.

When I tried the -r option (relocatable object) it wouldn't build, I put it in the same place in bmk_util.bmx and got the warning:
`using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking`.
So it seems the more complex option of the two.

**Comment by olejr** [comment]
Also, without this "fix", compilation of MaxIDE "work", but it's not runnable as in getting coredumps.
Happens on clean install of ubuntu 18.04 (or newer). Linux Mint 19 (based of ubuntu 18.04)
Installed Ubuntu/Mint in a VM, updated. downloaded latest release v0.99.3.31.
Recompiled modules, recompiled maxide. Try to run the new binary, coredump.

**Comment by woollybah** [comment]
There are repercussions to turning on this functionality. For example, any static libraries (like wxMax) would need to be built specifically with this option in order to be able to link against the application.

I got `-pie -fpie` working with a CC option of `-fpie` too, so I think I'll go with that. I've only tested some basic apps and MaxIDE so far, but it seems to be okay.

I think I'll enable it by default, but have a command-line option to disable it (`-no-pie`), just in case. And probably then another option in MaxIDE...

**Comment by markcwm** [comment]
Great, thanks Brucey. Yes static libraries would be too much trouble to recompile especially wxMax, glad you got it working with a CC option, seems like the way to go.

**Comment by GWRon** [comment]
> There are repercussions to turning on this functionality. For example, any static libraries (like wxMax) would need to be built specifically with this option in order to be able to link against the application.
> 
> I got `-pie -fpie` working with a CC option of `-fpie` too, so I think I'll go with that. I've only tested some basic apps and MaxIDE so far, but it seems to be okay.
> 
> I think I'll enable it by default, but have a command-line option to disable it (`-no-pie`), just in case. And probably then another option in MaxIDE...

Where to put the option to - is this an "developer option" ?

**Comment by woollybah** [comment]
The actual issue with double-clicking a PIE executable in a file manager is to do with the file manager itself, not the fact that the binary has been compiled with -fpie etc.

The Nautilus developers (for example) seem to expect a UI application to be installed and have a `.desktop` file which the file manager would use to indicate that the application needed to run when double-clicked.

**Comment by GWRon** [comment]
That is interesting. Thunar (xfce desktop) allows double clicking on "chmod +x"-ed files. For the fpie-compiled files the context menu-information screen doesn't allow to check the "allow to execute" checkbox (is hidden for these files).

Yet you might be right with the limitation being on the file manager side. Wonder why there is no update (for my mint 18.03 based install). Seems not backport worthy or the devs do not like the fpie-introduced requirements/needed changes.

**Comment by GWRon** [comment]
@ no-pie option
I asked where we should put this "Use -pie" (or how to call it) option to. I would create a commit/Pull Request then but am not sure how to name it - and where to put it. Maybe there is even a system call we could use to check if we should check that option or not (kind of a "version check") ?
