### ISSUE TITLE
Pie commit - binaries now classified as "shared library"

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bmk#65]
The latest commit (pie as default: https://github.com/bmx-ng/bmk/commit/8fc8042ae6d15e95965c78b9a84a53b0d98e1c82

leads to an error on my linux box:
```
[100%] Linking:GenusPrime.debug
g++ -m64 -pie -fpie -pthread -o /home/ronny/Arbeit/Programmieren/Projekte/GenusPrime/GenusPrime.debug /home/ronny/Arbeit/Programmieren/Tools/BlitzMaxNG/tmp/ld.tmp -L/usr/X11R6/lib -L/usr/lib -L/home/ronny/Arbeit/Programmieren/Tools/BlitzMaxNG/lib
collect2: fatal error: ld terminated with signal 6 [Abgebrochen]
compilation terminated.
/usr/bin/ld: ld: wcsrtombs.c:94: __wcsrtombs: Zusicherung Â»data.__outbuf[-1] == '\0'Â« nicht erfÃ¼llt.
Build Error: Failed to link /home/ronny/Arbeit/Programmieren/Projekte/GenusPrime/GenusPrime.debug
Process complete
```

**Comment by GWRon** [comment]
I reverted to the version before the commit (so replaced make.bmk and bmk again) and it compiled - so it seems to be exactly this commit

**Comment by GWRon** [comment]
This is still imminent - what to do, except of upgrading my linux distribution?

**Comment by GWRon** [comment]
I think for now you should be able to set a default in an external config file to be able to set "no pie" as default on older (and still maintained/updated) distributions.

**Comment by GWRon** [comment]
Recompiled modules ... and it works.

Dunno how to approach this - but maybe BMK could store a file of its revision/"api version" when compiling modules. So if there is some groundbreaking stuff changed in BMK this number increases. When compiling then BMK checks if the modules were "outdated" and if so, removes _any_ .i, .a. ...etc precompilates from the modules to enforce a proper recompilation.

Especially with "quick [scan]" stuff will else get missed here and there.

**Comment by woollybah** [comment]
Generally, any version number bump to bcc or bmk, you should consider a rebuild of your stuff, as things may have changed.
Of course, this is not an issue for people working only on a release version, just for those that are using the bleeding edge code.

**Comment by GWRon** [comment]
Yes this is true - but recompilation can... take a while (old 2 core cpu: brl and pub took release/debug each 30 minutes). This "compli-fication" could save some time - while of course adding the hassle of maintaining it.

**Comment by GWRon** [comment]
Files compiled with the new BMK (recompiled modules afterwards) are classified as "shared library" and not normal "binary".

**Comment by GWRon** [comment]
Users in the syntaxbomb forum describe similar problems.
https://www.syntaxbomb.com/index.php/topic,5613.msg25793/topicseen.html#new

They state that the fix provided by "markcwm" works while your (@woollybah) commit regarding no-pie does not work flawless.

**Comment by GWRon** [comment]
@woollybah  
you replied in #61 but I think it suits more to this issue here.

So your latest commit 1f35c1bcb5f650b5789dd6f90b64e926dc2f91d0 only changes params send if you set "nopie" - which isn't done when compiling with MaxIDE.

Also I am not sure what it effectively does - I've set:
bmk_config.bmx:
```BlitzMax
Global opt_nopie:Int
Global opt_nopie_set:Int
opt_nopie = 1
opt_nopie_set = 1
```
to disable "pie" - and it used the "unfixed" `-pie -fpie`. The resulting binaries seemed to work as expected (not sure about "double click").

The main culprit (for me - with my current desktop) should be unaffected by your commit: "pie"-enabled builds are not double-click-able in the file explorer. For reasons unknown to me - maybe it's what you wrote (file managers fault).
