### ISSUE TITLE
make.bmk: .ico, .settings, ... should fallback to %infile%

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bmk#68]
Coming from this thread:
https://www.syntaxbomb.com/index.php/topic,5536.new.html#new

When defining a custom %outfile% (via "-o outfile.exe") then make.bmk tries to use "outfile.ico", "outfile.rc" and the likes.
If they aren't found BMK should try to use the "defaults" at "infile.ico", "infile.rc" etc.

If BMK makes adjustments depending on build type (appending ".console" or ".debug") then the "fallback lookup" should take that into consideration too.

**Comment by Hezkore** [comment]
There's no reason to look in the output folder first; it only creates a unnecessary error.
The `.rc` file will always end up in the input/source folder anyways.
