### ISSUE TITLE
Quick compile ignores changes in included files of included files

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bmk#7]
## What happens? 

When changing content of an included file included from another file, this does not trigger recompilation.

## How to replicate

- create a file "test.bmx"
```BlitzMax
SuperStrict

include "test_include.bmx"
print "finished"
```
- create a file "test_include.bmx"
```BlitzMax

include "test_include_include.bmx"
```
- create a file "test_include_include.bmx"
```BlitzMax

print "I should trigger recompilation on changes"
```

Compile "test.bmx" and then change *test_include_include.bmx*. When now trying quick compile it does not recompile because it does not check the file date of that file.

Why?
bmk_make.bmx: __Method CalculateDependencies()__ does not recursively check all includes/incbins. So when compiling *test.bmx* it just checks the timestamp of *test_include.bmx" (and sets the timestamp of test.bmx accordingly) but skips *test_include_include.bmx*.

## How to solve:
For each included file the it should check the incbins like it does now but for each included file it should run that same function to load their incbins/includes (which then trigger that include/incbin-check again).
Short: needs some recursive functionality.

**Comment by GWRon** [comment]
Suggested change:

replace (Line 729 ff)
```BlitzMax
				If s Then
					' update our time to latest included time
					If s.time > source.time Then
						source.time = s.time
					End If
```

with
```BlitzMax
				If s Then
					' recursively fetch information from included files
					CalculateDependencies(s, isMod, rebuildImports)
					
					' update our time to latest included time
					If s.time > source.time Then
						source.time = s.time
					End If
```

**Comment by woollybah** [comment]
Thanks :smiley_cat:
