### ISSUE TITLE
"compilation" times longer because of file lookups

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bmk#8]
Not directly a bug or so ... but a notice.

On each compilation process BMK is comparing filetimes of all included and imported source files.

The more your project imports/includes (module and source file wise) the longer it takes.

I cannot come up with a general solution to this problem. I understand that the problem arises from the feature of dynamic compilation of requested modules.

One suggestion is to create an additional file in .bmx containing the last saved filename (not needed) and having a filetime of that modified file.
This would need a modified MaxIDE (file creation on "save"). It also would lead to problems when using other (text) editors.

So a better option would be to have a list of files per directory and let the system (OS) return the newest/latest touched file (timestamp).
Problem here is: I am not sure whether such a system call exists. Spawning processes ("ls") is creating to much overhead.
If there was an command ignoring provided filelists we would have to check if the newest is contained in our sources list...and if not, fall back to current approach.

For modules there is a potential solution: fileMtime of directories should change on creation of new files (directory index changes). So as we know that modules' .bmx-directory is only used by that module (compared to .bmx of a directory containing multiple projectXYZ.bmx) we could use that for our advantage.
When compiling a module a special file is unlinked (if existing) and regenerated...this should then trigger an index change (might need a clearstats call inbetween).
If that is not the case then we need up to two files (comptime1 and comptime2). Each compilation removes the one file and creates the other one... 

What does this do? It moves the filetime checks from per-project-compilation to a per-module-compilation. Projects are surely leas often compiled than projects.

Any other ideas?

**Comment by woollybah** [comment]
One option would be simply to not scan modules when building apps (just enough to check the .i and .a is available).
Perhaps a flag (-q for really quick, or something) would enable this mode - the default being to scan everything.

**Comment by GWRon** [comment]
Thought of that too...but it needs interaction of the end user... my extra-file-approach gets rid of that (by the costs of not working for non-module-code).

-q...
-q defaults to all-file-checks
-q1 is equivalent
-q2 is only checking project related files

**Comment by GWRon** [comment]
I have one more suggestion:

Plenty of the "makeSomething"-Functions have a param "rebuild:int". I would suggest, that all "filetime()"-checks are only done if "rebuild = false", else default to a minimum value as the file is already set for recompilation.

Is there a reason to have iface_time etc to be a "real" filetime even with rebuild set to true ? (maybe another file check utilizes this time but gets another rebuild-param - I do not know the code that deeply).

**Comment by GWRon** [comment]
Regarding my "module-cache"-idea:

- each time a module code is compiled, the file "modulename.release.linux.x86.time" is unlinked/created in "modulename.mod/.bmx". This should adjust the "fileMtime" of the ".bmx"-directory

- each time an app or module requires a module generically ("import bah.xml") it recompiles that module if:
  - no ".bmx"-directory existing
  - ".bmx"-directory is "more current" than the file importing the module

The problematic portion is (making the whole idea questionable... :-( ):
What happens, if I modify a modules source file after the ".time"-file was created. The rest of the autonomous system does not recognize the change automatically as the ".time"-file says "everything ok".

So in all cases the problem stays intact: without knowing the most current source file of an module / import /... you cannot check against some information cache.


Conclusion: the only way to decrease "filetime()"-count is to avoid fetching that data if you know already, that that specific file has to be rebuilt.


Seems I brought up a fruitless idea...

**Comment by woollybah** [comment]
As I mentioned previously, the only really viable path would be to have an option to run similar to the "legacy" mode of assuming that if the module .a and .i is there, it is the latest, and use those regardless of the rest of the source in the module.

**Comment by GWRon** [comment]
So it seems you just could shape off some "rebuild all"-compilation time by skipping filetime-checks then ...

Once again you were right ... I should stop coming up with "clever" ideas :camel:

**Comment by woollybah** [comment]
I've added new build flag for apps : -quick
This will only look at .i and .a files for modules, and only build that module if either is missing, otherwise, it assumes the .i and .a are the latest and will use those.
