### ISSUE TITLE
Alternative command operation names

### ISSUE THREAD

**Issue by Hezkore** [bmx-ng/bmk#81]
I think it would be nice if things like `-debug` and `-release` were supported, instead of just `-d` and `-r`.
It makes it easier to identify what's going on.
Same with `-a`; it could be `-all`.

**Comment by GWRon** [comment]
On *nix systems you will have `-d` or `--debug` (with double dash).

**Comment by woollybah** [comment]
Since our long-named options don't use a double-hyphen, there's probably no need to start doing it now.
It seems reasonable to have some more human-readable options if humans are likely to be reading them...

**Comment by GWRon** [comment]
Seems docs need an update then too

**Comment by Hezkore** [comment]
I'm never sure how GitHub notifies the repo owner, but I made a comment here - https://github.com/bmx-ng/bmk/commit/d892998894520b412de7aec75330490dda39ea9e#commitcomment-33808197

**Comment by GWRon** [comment]
Everyone gets an email if:
Owner of the commit/issue
Or
Commenting person


So I got one.

**Comment by woollybah** [comment]
I saw it too ;-)
