### ISSUE TITLE
Create output folder operation

### ISSUE THREAD

**Issue by Hezkore** [bmx-ng/bmk#82]
To use the `-o` operation; you have to specify a path that exists.
I suggest a `-c` operation (or similar) that creates the output path if it doesn't exist.

I for example do not build to the source folder.
I build to "../build/release/" for release builds.
And "../build/debug/" for debug builds.
But I always have to create the `build`, `debug` and `release` folders beforehand.
Which is pretty annoying.

**Comment by GWRon** [comment]
I think there is no need for an additional parameter ... BMK/BCC should just (try to) create a directory if it is missing.

**Comment by GWRon** [comment]
I pushed a fix to "BMK" - as it already tries that on Mac when creating sub-folders. So it should try for the main folder now too ;-)
