### ISSUE TITLE
windres fails if path has spaces

### ISSUE THREAD

**Issue by Hezkore** [bmx-ng/bmk#89]
'windres' fails to add icon and settings if the path include spaces.
A simple way of testing this is to just name your BlitzMax folder to something like "Blitz Max NG" and compiling some sample that comes with BMX.

`[100%] Linking:breakout.exe
'D:/Applications/Blitz' is not recognized as an internal or external command, operable program or batch file.
D:/Applications/Blitz Max NG/MinGW32x64/bin/windres.exe: preprocessing failed.
Executing:breakout.exe`

**Comment by woollybah** [comment]
Are you using the latest, bmk (and its make.bmk) ?
As far as I can see, from looking at the code (in make.bmk), it's wrapping the paths in quotes.

**Comment by Hezkore** [comment]
I'm using the latest release from the blitzmax.org website at least.
I have not compiled from source myself.

Here's a video of the process:
http://hezkore.com/junk/2019-06-19_17-40-54.mp4

If I rename the folder to "BlitzMaxNG"; windres runs just fine.
`[100%] Linking:breakout.exe
Executing:breakout.exe
Process complete`

**Comment by woollybah** [comment]
Can you please turn on `verbose` and paste the `windres` line?

For example, mine looks like this :
```
"D:/000_programming/BlitzMaxNG/MinGW32x64/bin/windres.exe" -i "D:/000_programming/source/maxide_git/.bmx/maxide.x64.rc" -o "D:/000_programming/source/maxide_git/.bmx/maxide.x64.res.o"
```
Since all the parts are wrapped in quotes, I wouldn't normally expect there to be an issue with spaces...

In the meantime, I'll set up a new NG instance and test it out myself...

**Comment by Hezkore** [comment]
`"D:/Applications/Blitz Max NG/MinGW32x64/bin/windres.exe" -i "D:/Applications/Blitz Max NG/samples/breakout/.bmx/breakout.x64.rc" -o "D:/Applications/Blitz Max NG/samples/breakout/.bmx/breakout.x64.res.o"
[100%] Linking:breakout.exe
"D:/Applications/Blitz Max NG/MinGW32x64/bin/g++.exe" -Wl,--stack,4194304 -s  -Wl,--subsystem,windows -mwindows -mthreads -static -o "D:/Applications/Blitz Max NG/samples/breakout/breakout.exe" "D:/Applications/Blitz Max NG/tmp/ld.tmp"
'D:/Applications/Blitz' is not recognized as an internal or external command,
operable program or batch file.
D:/Applications/Blitz Max NG/MinGW32x64/bin/windres.exe: preprocessing failed.
`

**Comment by woollybah** [comment]
Thanks. It appears to be a well-known "feature" of `windres` :-)

I'll see if I can find a workaround.

**Comment by woollybah** [comment]
So... taking the command line that is run by bmk, and adding `-v`, it shows that `windres` attempts to run `gcc` in order to generate something...
```
D:/000_programming/releases/build_area/may/BlitzMax test/MinGW32x64/bin/gcc -E -xc -DRC_INVOKED  "D:\000_programming\releases\build_area\may\BlitzMax test\samples\breakout\.bmx\breakout.x64.rc"
```
However, since `gcc` is also in a location that contains a space, and the path to gcc is not wrapped in quotes, this command fails, resulting in the error.

I can't really see much else we can do to fix this, without either, 
1) recommend to use BlitzMax in a location that does not have spaces.
2) Use an installation of MinGW in a location without spaces
3) bundle a "fixed" copy of windres. (I don't know where I'd get one of these, currently)

**Comment by Hezkore** [comment]
Maybe add to the docs that `windres` only works with paths that has no spaces.
And I guess add a warning to the build output as well...
A warning similar to the function argument casting issues would work well in my case, because the VSCode extension I'm making for BlitzMax could pick up on it and display it in the "Problems" panel.

**Comment by GWRon** [comment]
Is it this?
https://sourceware.org/bugzilla/show_bug.cgi?id=4356

It contains a kind of bugfix.


Aside of that... When Windows had long filenames the first time you most probably came across "C:\Progra~1". Can't we use a library/tool which gives us the 8.3-based file path (so with tilde etc?).
Pass this to windres then.

**Comment by Hezkore** [comment]
A cheap and hacky way of doing it I guess would be to actually copy `windres` to the folder where the source is.
That way you wouldn't have to include the absolute path, just do like "breakout.whatever", and the spaces wouldn't be an issue.
Then remove `windres` from the folder.

**Comment by GWRon** [comment]
Had this copy-stuff-to-project in mind too. Of course only if the path contains spaces (to minimize amount of affected users).

**Comment by woollybah** [comment]
The issue is the path that `windres` itself uses to refer to `gcc`. The other paths are already wrapped with quotes, and are not the problem. i.e. The "path to gcc" also needs to be wrapped in quotes, which `windres` is not doing.

We might need to cwd to windres' location first, before we can run it.

**Comment by GWRon** [comment]
I thought of CWD too..but then assumed that windred might still resolve absolute paths which wouldn't help then.

Wonder why they did not fix it during the last... 10+ years of long filenames.
