### ISSUE TITLE
LoadLibraryA ?

### ISSUE THREAD

**Issue by Wiering** [bmx-ng/bmk#96]
Nice to find a new version of BlitzMax! 
While trying to get one of my old programs to work I ran into this error:  Compile Error
Identifier 'loadlibrarya' not found.
Any ideas?

```
?win32
  Global GetFileAttributes: Int (lpFileName: Byte Ptr) = GetProcAddress (LoadLibraryA ("Kernel32"), "GetFileAttributesA")
?
```

**Comment by Kerntrick** [comment]
I think you need to import Pub.Win32

**Comment by Wiering** [comment]
Thanks, that worked.
