### ISSUE TITLE
modules not taking modified incbin file into account when compiling

### ISSUE THREAD

**Issue by davecamp** [bmx-ng/bmk#99]
Hiya,

When modifying a module file it's nice that you can hit 'compile' and the build system will pick up and compile just the modified module and any dependent files, but it doesn't detect any modified incbin files when building this way.
Turning on or off 'Quick Scan' option doesn't resolve this either.

Hitting 'Compile Modules' (CTRL + D)  *DOES* pick up the modified incbin file as expected.

**Comment by GWRon** [comment]
Hmm .. I thought there was something done to take incbin stuff into account ... maybe it became no longer working properly or I mix it up with something else.

Maybe it does not work as it creates the incbin file - but during module compilation it does not know "what" files the module code incbinned - and so they do not check them for changes.


Only way - I can think of - is to utilize a "last modified" time-stamp for the directory - but this is not guaranteed to work.

**Comment by davecamp** [comment]
How come a timestamp related solution is not guaranteed to work?

**Comment by GWRon** [comment]
The timestamp of an incbin.whatever.c does not relate to the timestamp of files incbinned there.


When bmk checks what to compile...it checks the incbin.whatever.c ...but does not know about the files incbinned there...and their current timestamp.

**Comment by davecamp** [comment]
'filetoincbin.whatever' gets converted to the raw byte form as 'filetoincbin.c'

the compiler should really be checking and comparing the timestamps of these 2 files. ie the 'source' versus the 'compiled'.

**Comment by GWRon** [comment]
ahh ok .. so it is not a "collectionoffiles.incbin.c" ok... then yes, it could "check" the original files then.

**Comment by woollybah** [comment]
I believe this has been fixed.
